// Created by Ronis Vision. All rights reserved
// 28.06.2020 01:58:37
// ======AUTOGENERATED - DONT EDIT======

namespace RVModules.RVLoadBalancer.Tasks
{
    public interface IDummyMonoBehaviour 
    {
        #region Properties
        #endregion
        #region Methods
        #endregion
    }
}