// Created by Ronis Vision. All rights reserved
// 28.06.2020 01:48:17
// ======AUTOGENERATED - DONT EDIT======

namespace RVModules.RVLoadBalancer.Tasks
{
    public interface ILoadBalancedTaskBase 
    {
        #region Properties
        #endregion
        #region Methods
        #endregion
    }
}