// Created by Ronis Vision. All rights reserved
// 26.06.2020 06:31:55
// ======AUTOGENERATED - DONT EDIT======

namespace RVModules.RVLoadBalancer.Tasks
{
    public interface ITimeIntervalLoadBalancer 
    {
        #region Properties
        #endregion
        #region Methods
        void Tick(float _deltaTime);
        #endregion
    }
}